In [2]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import model
import time
from datetime import datetime
from datetime import timedelta
sns.set()

In [4]:
df = pd.read_csv('dataset/BTC-sentiment.csv')
date_ori = pd.to_datetime(df.iloc[:, 0]).tolist()
df.head()

             timestamp         close  positive  negative
0  2019-08-09T23:00:00  11860.074544  0.672896  0.327104
1  2019-08-09T23:20:00  11872.025879  0.595100  0.404900
2  2019-08-09T23:40:00  11880.504557  0.596702  0.403298
3  2019-08-10T00:00:00  11918.873481  0.577972  0.422028
4  2019-08-10T00:20:00  11937.581272  0.585342  0.414658

In [5]:
df

               timestamp         close  positive  negative
0    2019-08-09T23:00:00  11860.074544  0.672896  0.327104
1    2019-08-09T23:20:00  11872.025879  0.595100  0.404900
2    2019-08-09T23:40:00  11880.504557  0.596702  0.403298
3    2019-08-10T00:00:00  11918.873481  0.577972  0.422028
4    2019-08-10T00:20:00  11937.581272  0.585342  0.414658
..                   ...           ...       ...       ...
334  2019-08-14T14:20:00  10529.615560  0.554100  0.445900
335  2019-08-14T14:40:00  10502.307726  0.603816  0.396184
336  2019-08-14T15:00:00  10532.066840  0.632476  0.367524
337  2019-08-14T15:20:00  10515.261914  0.593976  0.406024
338  2019-08-14T15:40:00  10513.206706  0.442508  0.557492

[339 rows x 4 columns]